name: dry-publish

on: push
jobs:
  dry-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Publish
        uses: caseyhillers/actions-flutter-pub-publisher@v1.5.1
        with:
          credential: ${{ secrets.CREDENTIAL_JSON }}
          flutter_package: false
          dry_run: true