name: toaster_next
description: Yet another Flutter Toaster. Built with ease of use and testablility in mind, with sensible defaults.
version: 1.1.0
homepage: https://github.com/antholeole/toaster_next

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  clock: ^1.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  mocktail: ^0.3.0
  fake_async: ^1.2.0


flutter:
