name: local_user
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.16.2 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
dependencies: 
  local_value: ^1.1.1
  uuid_type_next:
    git:
      url: https://github.com/antholeole/ants_packages.git
      path: uuid_type_next
  flutter:
    sdk: flutter
    version: ^0.0.0
