name: uuid_type_next
description: A UUID library with Json and built_value converters.
homepage: https://github.com/antholeole/ants_packages/tree/main/uuid_type_next
version: 1.0.0

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  built_value: ^8.2.3
  json_annotation: ^4.5.0
  uuid: ^3.0.6

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
