name: local_value
description: A simple abstraction to persist data in the local file system.
version: 1.2.0
repository: https://github.com/antholeole/ants_packages/tree/main/local_data_manager

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^2.0.9
  shared_preferences: ^2.0.13
  flutter_secure_storage: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  mocktail: ^0.3.0


flutter:

