name: local_value
description: A simple abstraction to persist data in the local file system.
version: 1.1.1
repository: https://github.com/antholeole/local_value

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^2.0.9
  shared_preferences: ^2.0.13
  flutter_secure_storage: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  mocktail: ^0.2.0


flutter:

